#热部署
#spring:
#  devtools:
#    restart:
#      enabled: true
#      additional-paths: src/main/resources,src/main/java
#      exclude: /WEB-INF/**
#  #环境选择
#  profile:
#    active: online




name: xiaodai
url: www.118.system.hahu.edu.com

spring:
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000
#    Thymeleaf 模板
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名



